#
# Pebble build script. The detector core (src/core) is compiled into BOTH
# the foreground app and the background worker.
#
import os.path

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')
    # Debug builds: CM_DEFINES="CM_WORKER_VERBOSE=1 CM_VIBE_DIAG=1" pebble build
    extra_defines = os.environ.get('CM_DEFINES', '').split()

    build_worker = os.path.exists('worker_src')
    binaries = []

    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        if extra_defines:
            ctx.env.append_value('DEFINES', extra_defines)
        ctx.set_group(ctx.env.PLATFORM_NAME)

        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_build(
            source=ctx.path.ant_glob(['src/c/**/*.c', 'src/core/**/*.c']),
            target=app_elf,
            bin_type='app')

        if build_worker:
            worker_elf = '{}/pebble-worker.elf'.format(ctx.env.BUILD_DIR)
            binaries.append({'platform': platform,
                             'app_elf': app_elf,
                             'worker_elf': worker_elf})
            ctx.pbl_build(
                source=ctx.path.ant_glob(['worker_src/c/**/*.c',
                                          'src/core/**/*.c']),
                target=worker_elf,
                bin_type='worker')
        else:
            binaries.append({'platform': platform, 'app_elf': app_elf})
    ctx.env = cached_env

    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries,
                   js=ctx.path.ant_glob(['src/pkjs/**/*.js']),
                   js_entry_file='src/pkjs/index.js')
